///|
test "bold text" {
  println(bold("bold text"))
}

///|
test "underline text" {
  println(underline("underline text"))
}

///|
test "red text" {
  println(red("red text"))
}

///|
test "green text" {
  println(green("green text"))
}

///|
test "blue text" {
  println(blue("blue text"))
}

///|
test "bg white text" {
  println(bgWhite("bg white text"))
}

///|
test "bg blue bright text" {
  println(bgBlueBright("bg blue bright text"))
}
